### ISSUE TITLE
安装器报错：current environment does not contain support for asyncio.events:AbstractEventLoop

### ISSUE THREAD

**Issue by icesakura** [Haibersut/chatgpt-installer#3]
原python环境已卸载，miniconda安装正常，安装器出现如下报错：

[2023-08-07 21:03:37.936] [info] 启动程序
2023-08-07 21:03:44.273 | SUCCESS  | config:scan_presets:565 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-08-07 21:03:44.273 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-08-07 21:03:44.274 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl <==> ./presets\catgirl.txt [成功]
2023-08-07 21:03:44.275 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]
2023-08-07 21:03:44.275 | SUCCESS  | config:scan_presets:578 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2023-08-07 21:03:44.275 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-08-07 21:03:44.540 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有正常退出。
2023-08-07 21:03:44.540 | ERROR    | utils.exithooks:foo:36 - current environment does not contain support for asyncio.events:AbstractEventLoop
NoneType: None
2023-08-07 21:03:44.541 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解决方案：
2023-08-07 21:03:44.542 | ERROR    | utils.exithooks:foo:38 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x0000020492337880>
Traceback (most recent call last):
  File "D:\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\utils\exithooks.py", line 39, in foo
    raise hooks.exception
  File "D:\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\bot.py", line 12, in <module>
    loop = creart.create(AbstractEventLoop)
  File "C:\Users\lusha\Miniconda3\envs\chatgpt\lib\site-packages\creart\__init__.py", line 60, in create
    _assert_supported(target_type)
  File "C:\Users\lusha\Miniconda3\envs\chatgpt\lib\site-packages\creart\__init__.py", line 48, in _assert_supported
    raise TypeError(f"current environment does not contain support for {_signature(target)}")
TypeError: current environment does not contain support for asyncio.events:AbstractEventLoop
[2023-08-07 21:03:44.636] [info] 按任意键退出...

**Comment by Haibersut** [comment]
这个是graia机器人框架的问题，你可以看看主项目有一个类似的issue，更新依赖可以解决，我要等一会替换一下2.5.3



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月7日(周一) 晚上9:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Haibersut/chatgpt-installer] 安装器报错：current environment does not contain support for asyncio.events:AbstractEventLoop (Issue #3)




 
原python环境已卸载，miniconda安装正常，安装器出现如下报错：
 
[2023-08-07 21:03:37.936] [info] 启动程序
 2023-08-07 21:03:44.273 | SUCCESS  | config:scan_presets:565 - 检查预设：聊天 <==&gt; presets/issue402.txt [成功]
 2023-08-07 21:03:44.273 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <==&gt; presets/catgirl.txt [成功]
 2023-08-07 21:03:44.274 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl <==&gt; ./presets\catgirl.txt [成功]
 2023-08-07 21:03:44.275 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl_en <==&gt; ./presets\catgirl_en.txt [成功]
 2023-08-07 21:03:44.275 | SUCCESS  | config:scan_presets:578 - 注册预设：issue402 <==&gt; ./presets\issue402.txt [成功]
 2023-08-07 21:03:44.275 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模板 <==&gt; ./presets\预设模板.txt [成功]
 2023-08-07 21:03:44.540 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有正常退出。
 2023-08-07 21:03:44.540 | ERROR    | utils.exithooks:foo:36 - current environment does not contain support for asyncio.events:AbstractEventLoop
 NoneType: None
 2023-08-07 21:03:44.541 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解决方案：
 2023-08-07 21:03:44.542 | ERROR    | utils.exithooks:foo:38 - lss233/chatgpt-mirai-qq-bot#85
 Exception ignored in atexit callback: <function foo at 0x0000020492337880&gt;
 Traceback (most recent call last):
 File "D:\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\utils\exithooks.py", line 39, in foo
 raise hooks.exception
 File "D:\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\bot.py", line 12, in 
 loop = creart.create(AbstractEventLoop)
 File "C:\Users\lusha\Miniconda3\envs\chatgpt\lib\site-packages\creart_init_.py", line 60, in create
 assert_supported(target_type)
 File "C:\Users\lusha\Miniconda3\envs\chatgpt\lib\site-packages\creart_init.py", line 48, in _assert_supported
 raise TypeError(f"current environment does not contain support for {_signature(target)}")
 TypeError: current environment does not contain support for asyncio.events:AbstractEventLoop
 [2023-08-07 21:03:44.636] [info] 按任意键退出...

**Comment by singularity2000** [comment]
如何在你替换完成后 第一时间收到通知😳

**Comment by Haibersut** [comment]
我提醒你233



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月7日(周一) 晚上9:32
收件人: ***@***.***&gt;;
抄送: "Matt ***@***.******@***.***&gt;;
主题: Re: [Haibersut/chatgpt-installer] 安装器报错：current environment does not contain support for asyncio.events:AbstractEventLoop (Issue #3)




 
如何在你替换完成后 第一时间收到通知😳

**Comment by Haibersut** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1134
